/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MarkPerry' at '13/07/15 10:56 PM' with Gradle 2.4
 *
 * @author MarkPerry, @date 13/07/15 10:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
